- doc/directives.md
I found the existing explaination a bit hard to follow, this is my attempt to make it a bit clearer.
> docs: clarify what `otk.target` means

- example/fedora/minimal.yaml
- example/fedora/osbuild/pipelines/tree.yaml
For a lot of the OS customizations we really only change a single option. It would be nice to express this in a shorter way and I tried to capture it in this commit. Essentially the customization just moves a level deeper which AIUI is something that is already allowed with the current way customizations are specified.
> RFC: simplify customizations in the tree.yaml

- README.md
... pretty obvious but why not document
> README: document pytest usage

- doc/directives.md
> doc: clarify directive placement

- .github/workflows/lint.yml
These tests have already ran during the merge_queue.
> ci: remove test-on-main

- .github/workflows/lint.yml
We weren't installing dev deps.
> ci: fix up install

- README.md
Include that it means `main` *might* be broken.
> readme: clarify poc state some more

- example/centos/centos-9-x86_64-ami.yaml
- example/centos/centos-9-x86_64-qcow2.yaml
- example/centos/common/centos-9.yaml
- example/centos/fragment/chrony.yaml
- example/centos/fragment/files.yaml
- example/centos/fragment/keymap.yaml
- example/centos/fragment/locale.yaml
- example/centos/fragment/user.yaml
- example/fedora/osbuild/stage/hostname.yaml
- example/fedora/osbuild/stage/locale.yaml
- example/fedora/osbuild/stage/timezone.yaml
The new name was decided to avoid confusion with the existing concept of "customizations" in images/composer.
> examples: replace "customization" with "modification"

- doc/00-installation.md
- doc/01-contributing.md
- doc/02-usage.md
- doc/06-security.md
Let's expand our documentation situation some more.
> doc: expand

- doc/03-omnifest/index.md
- example/fedora/minimal-40-aarch64.yaml
- example/fedora/minimal-40-x86_64.yaml
- src/otk/command.py
- src/otk/external.py
- test/test_command.py
- test/test_compile.py
- test/test_validate.py
I also fixed the behavior of "output" as it was expected to be a path - which is wrong I guess
fixes #79
> otk/command: implement "validate" command

- src/otk/command.py
- src/otk/context.py
- src/otk/document.py
- src/otk/external.py
- src/otk/tree.py
- src/otk_osbuild/command.py
Purely whitespace/automatic changes.
Followup for https://github.com/osbuild/otk/pull/108
> otk: run `ruff format` with the new 120 line default

- .github/workflows/build.yaml
- .github/workflows/lint.yml
`yamllint` considers `on` to be a truthy value. Quote it to turn it into a string.
> lint: quote "on" in yaml

- .github/workflows/test.yml
- pyproject.toml
Small workflow so that we run the unit tests as part of our PR workflow.
> gh: add workflow to run tests as part of each PR

- doc/03-omnifest/01-directive.md
> doc: trivial update for `desugar` -> substitution

- src/otk/command.py
- src/otk/document.py
- test/data/base/05-target-in-include.yaml
- test/data/base/05-target-in-include.yaml.disabled
- test/test_document.py
Delay the target verification until *after* processing includes, fixes #112.
> delay target verification

- src/otk/traversal.py
- test/test_traversal.py
Thanks to Achilleas for suggesting this.
> otk: make the ciruclar import error nicer

- src/otk/command.py
- test/data/base/12-op-join-type.yaml
- test/test_command.py
- test/test_compile.py
- test/test_example.py
...including some tests - which could be written more readable I guess
> otk/command: fix handling of argument '-t'

- test/test_command.py
Hinted by @mvo5 in https://github.com/osbuild/otk/pull/152#pullrequestreview-2147953846 
to improve readability and decrease code duplication
> test/test_command: improve test input readability

- .github/workflows/test.yml
- example/centos/centos-9-x86_64-ami.yaml
- example/centos/centos-9-x86_64-qcow2.yaml
- example/fedora/minimal-40-aarch64.yaml
- example/fedora/minimal-40-x86_64.yaml
- example/fedora/osbuild/pipeline/tree.yaml
- example/fedora/repository/40/repositories.yaml
this commit fix compile problems in minimal-40-aarch64.yaml and minimal-40-x86_64.yaml files.
> fedora: fix fedora compile

- .pre-commit-config.yaml
- Makefile
…while replacing the call also in `Makefile`
> pre-commit: add mypy

- Makefile
this makes `make test` more granular and `make push-check` covering all
> Makefile: introduce `make push-check`

- Makefile
> Makefile: add check for pre-commit also for target 'type'

- test/data/images-ref/centos/9/x86_64/ami/centos_9-x86_64-ami-empty.json
Generated using `./test/data/images-ref/gen-image-def` for test reference. In the future, these will be generated on-demand for testing as long as we need them.
> test: x86 ami import

- example/centos/centos-9-aarch64-ami.yaml
- test/data/images-ref/centos/9/aarch64/ami/centos_9-aarch64-ami-empty.json
- test/data/images-ref/centos/9/aarch64/ami/centos_9-aarch64-ami-empty.yaml
> example/centos: ami for aarch64

- example/centos/centos-9-aarch64-image-installer.yaml
- example/centos/centos-9-x86_64-image-installer.yaml
- test/data/images-ref/centos/9/aarch64/image-installer/centos_9-aarch64-image_installer-empty.yaml
- test/data/images-ref/centos/9/x86_64/image-installer/centos_9-x86_64-image_installer-empty.yaml
Generated image references and deduplicated omnifests.
> example: x86 and aarch64 for image-installer

- example/centos/centos-9-x86_64-oci.yaml
- test/data/images-ref/centos/9/x86_64/oci/centos_9-x86_64-oci-empty.yaml
Generate reference manifests for the OCI image and do an initial implementation of the omnifests. Based on #219.
> example/centos: import OCI

- example/centos/centos-9-aarch64-ami.yaml
- example/centos/centos-9-aarch64-edge-commit.yaml
- example/centos/centos-9-aarch64-image-installer.yaml
- example/centos/centos-9-aarch64-minimal-raw.yaml
- example/centos/centos-9-aarch64-qcow2.yaml
- example/centos/centos-9-aarch64-tar.yaml
- example/centos/centos-9-aarch64-vhd.yaml
- example/centos/centos-9-ppc64le-tar.yaml
- example/centos/centos-9-s390x-tar.yaml
- example/centos/centos-9-x86_64-ami.yaml
- example/centos/centos-9-x86_64-edge-commit.yaml
- example/centos/centos-9-x86_64-image-installer.yaml
- example/centos/centos-9-x86_64-minimal-raw.yaml
- example/centos/centos-9-x86_64-ova.yaml
- example/centos/centos-9-x86_64-qcow2.yaml
- example/centos/centos-9-x86_64-tar.yaml
- example/centos/centos-9-x86_64-vhd.yaml
- example/centos/centos-9-x86_64-vmdk.yaml
- example/centos/fragment/timezone.yaml
Introduce a new timezone fragment. Split off from #240.
> example/centos: timezone fragment

- example/centos/centos-9-aarch64-wsl.yaml
- example/centos/centos-9-x86_64-wsl.yaml
- test/data/images-ref/centos/9/aarch64/wsl/centos_9-aarch64-wsl-empty.yaml
- test/data/images-ref/centos/9/x86_64/wsl/centos_9-x86_64-wsl-empty.yaml
Generate test manifests for the WSL image types and implement their initial omnifests.
> example/centos: import WSL

- example/centos/centos-9-aarch64-ami.yaml
- example/centos/centos-9-aarch64-edge-commit.yaml
- example/centos/centos-9-aarch64-image-installer.yaml
- example/centos/centos-9-aarch64-minimal-raw.yaml
- example/centos/centos-9-aarch64-qcow2.yaml
- example/centos/centos-9-aarch64-tar.yaml
- example/centos/centos-9-aarch64-vhd.yaml
- example/centos/centos-9-ppc64le-tar.yaml
- example/centos/centos-9-s390x-tar.yaml
- example/centos/centos-9-x86_64-ami.yaml
- example/centos/centos-9-x86_64-edge-commit.yaml
- example/centos/centos-9-x86_64-image-installer.yaml
- example/centos/centos-9-x86_64-minimal-raw.yaml
- example/centos/centos-9-x86_64-ova.yaml
- example/centos/centos-9-x86_64-qcow2.yaml
- example/centos/centos-9-x86_64-tar.yaml
- example/centos/centos-9-x86_64-vhd.yaml
- example/centos/centos-9-x86_64-vmdk.yaml
- example/centos/fragment/selinux/targeted.yaml
Initial SELinux fragment for targeted without extra labels. Split off from #240.
> example/centos: selinux fragment

- example/centos/centos-9-s390x-qcow2.yaml
- example/centos/common/partition-table/s390x/default.yaml
- example/centos/pipeline/image/s390x.yaml
- test/data/images-ref/centos/9/s390x/qcow2/centos_9-s390x-qcow2-empty.yaml
initial version of the example for centos 9 s390x qcow2
> example/centos: qcow2 for s390x

- Makefile
- example/centos/centos-9-aarch64-ami.yaml
- example/centos/centos-9-aarch64-minimal-raw.yaml
- example/centos/centos-9-aarch64-qcow2.yaml
- example/centos/centos-9-aarch64-vhd.yaml
- example/centos/centos-9-s390x-qcow2.yaml
- example/centos/centos-9-x86_64-ami.yaml
- example/centos/centos-9-x86_64-minimal-raw.yaml
- example/centos/centos-9-x86_64-ova.yaml
- example/centos/centos-9-x86_64-qcow2.yaml
- example/centos/centos-9-x86_64-vhd.yaml
- example/centos/centos-9-x86_64-vmdk.yaml
- example/centos/common/partition-table/aarch64/default.yaml
- example/centos/common/partition-table/aarch64/minimal-raw.yaml
- example/centos/common/partition-table/aarch64/vhd.yaml
- example/centos/common/partition-table/s390x/default.yaml
- example/centos/common/partition-table/x86_64/default.yaml
- example/centos/common/partition-table/x86_64/minimal-raw.yaml
- example/centos/common/partition-table/x86_64/vhd_vmdk_ova.yaml
- example/centos/pipeline/image/aarch64.yaml
- example/centos/pipeline/image/s390x.yaml
- example/centos/pipeline/image/x86_64-no-bios.yaml
- example/centos/pipeline/image/x86_64.yaml
The externals [got renamed](https://github.com/osbuild/images/pull/922) in `images`. Let's rename them here to unblock tests.
> example: rename externals

- README.md
Let's write this down so people don't invest into the project for now.
> readme: document discontinuation
