doc/directives.md
The spec currently defines two ways to use variables. All the examples use only a single one even in places that are technically not allowing it. But I have to say I really like the short form this RFC advocates to just start with that short form and see if we actually have a use case for the long form.
The rule would be simple:
- string vars can be used inside strings "foo: hello $world" works if "world" is a string
- non-string vars must stand on their own, so "foo: $world" is the only allowed form for maps/seq etc.
=> RFC: start without `otk.variable` just `$`

doc/directives.md, example/fedora/minimal.yaml, example/fedora/osbuild/pipelines/root.yaml, example/fedora/osbuild/pipelines/tree.yaml, example/fedora/repositories/40.yaml
With curl dollar var substition some ambitious cases become slightly easier to see without knowning about the var content, e.g.:
```
$foo.bar
```
could mean "replace $foo" and add ".bar" if `$foo` is a string or "use member bar of map $foo". With
```
${foo}.bar
${foo.bar}
```
this would become easier to see without having context what type the var is.
=> RFC: use curl dollar (`${}`) for var substituion

example/fedora/osbuild/custom/file.yaml
Makes `file.yaml` at least valid for now so #10 can be merged.
=> example: change file.yaml to pass lint

doc/directives.md, example/fedora/fedora-39-amd64.yaml, example/fedora/minimal.yaml
The use-case given (and maybe I'm missing other use-cases here) for the otk.arguments is currently "version" and "architecture".
We could do this instead via a `fedora-39-amd64.yaml` file that just define those arguments. The upside of this is that we can easily see what combinations of version and architecture we support by looking at the top-level dir. It also simplifies the spec and we would not have to worry about validating arguments, i.e. how do we know that "-Dversion=41" is valid or not (if not valid it would probably mean down the line an include based on the version cannot be found and that presents challenges for a nice error message).
It would also allow us to have symlinks when things do not change, e.g.
```
rhel-9.3.yaml -> rhel-9.4.yaml
```
But maybe I'm missing another use …
=> RFC: use otk files instead of otk.arguments

test/test_sugar.py
I implemented some test, just to understand the project a little bit.
the expected_error probably will (should) improve? - but that can be done iteratively I guess
... and is this on purpose that resolve() changes the given variable in place?
=> test: implement simple sugar test

.github/workflows/lint.yml
Enable ci on the merge queue, thanks @ondrejbudai.
=> ci: enable lint workflow on merge queue

.spellcheck-en-custom.txt, README.md
Some minor updates to the readme to re-order, make the pre-commit link a bit prettier, and to include our generic project blurb.
=> readme: updates again

src/otk/transform/__init__.py, test/test_transform.py
This copies the tree for each transform giving the lower lying transforms a new tree every time.
=> transform: copy the tree instead of in-place

doc/directives.md, example/fedora/minimal-40-x86_64.yaml, example/fedora/osbuild/buildroot.yaml
The word `root` has many meanings and in minimal-40-x86_64 it is used twice, once for the buildroot and once for the root of the filesystem. It seems slightly nicer to spell the buildroot out as `buildroot` even if it's a little bit more typing.
=> [RFC] doc,example: rename `root` to `buildroot`

example/fedora/minimal-40-aarch64.yaml, example/fedora/minimal-common.yaml
Tweak the example to be slightly more realistic and have two arches for fedora and a common yaml. This will probably see more refactor when an additonal fedora that is not minimal is added.
Tiny starting point, if this looks okay I will play a bit more with how fedora maybe in two arches and two flaviors could look like :)
=> [RFC] examples: split out "fedora/minimal-common.yaml" and define two archs

.spellcheck-en-custom.txt, README.md, doc/00-installation.md, doc/01-contributing.md, doc/02-usage.md, doc/03-omnifest/01-directive.md, doc/03-omnifest/02-external.md, doc/03-omnifest/index.md, doc/04-best-practices.md, doc/05-deprecation.md, doc/06-security.md, doc/07-integration.md, doc/index.md
I had moved the documentation into the main docs: https://github.com/osbuild/osbuild.github.io/pull/79
However it is more useful during the poc state of the project to have the documentation exist together with the source code.
=> re-import documentation

doc/03-omnifest/01-directive.md
There is no `otk.variable` anymore right now, all variable substitution is done via ${}.
=> directive.md: remove otk.variable and replace with ${}

example/fedora/osbuild/custom/file.yaml
This example seems to be outdated (it still uses the `mtk` prefix) and it's not used.
=> examples: remove the `custom/file.yaml` file example

example/fedora/minimal-40-aarch64.yaml, example/fedora/minimal-40-x86_64.yaml, example/fedora/minimal-common.yaml
Without at least two consumers of `minimal-common.yaml` the extraction
of the common definitions is a bit pointless :) So this commmits
adds one more consumer.
---
Recent commits adds content from "minimal-common.yaml" to the
"minimal-40-aarch64.yaml". This commit de-duplicates that again.
[I'm not sure I got this 100% correct, please double check that I really transferred the pieces in the right places]
=> examples: de-duplicate, add one more arch

doc/03-omnifest/01-directive.md, src/otk/directive.py, test/test_directive.py
I wonder if we can simply avoid having the user care about the type when doing a join operation. It seems mostly a burden to the user and we need to check during compilation of the otk file anyway so maybe we can just leave it out?
P.S. Having an example use-case for both would be really good, I'm wonder if we only should add things to the spec once we actually use it in the example/* tree ?
=> RFC: define a single `otk.op.join`

Makefile, otk.spec
This adds the srpm and rpm build makefile targets (borrowed from osbuild), and uses the pyproject rpm macros to support pyproject.toml The version is hard-coded into the spec so it will need to be changed at the same time as the version in pyproject.toml
Fixes #44
=> spec: Add a basic spec and Makefile targets

pyproject.toml
Due to #43 we won't be able to use parsimonious. This PR drops it as it wasn't in use yet.
=> deps: remove parsimonious

pyproject.toml, src/otk/command.py
Due to #43 we figured out that we can't use `rich`, the relevant issue for this is #68. Let's remove rich, it is only used for pretty logging output.
=> deps: remove rich

.spellcheck-en-custom.txt, src/otk/command.py, src/otk/target.py
This PR allows unknown targets and outputs them as JSON.
=> allow unknown targets

src/otk/context.py, test/test_directive.py, test/test_directive_define.py
`otk.define` is incorrectly handling overwriting values by not overwriting them at all. Let's fix it and add a test.
=> directive: define fix

.github/workflows/build.yaml
This is useful when you want pin the image. Also, it's very helpful
to easily see which commit was used to build container image.
=> ci: tag main builds with their git commit SHA

src/otk_osbuild/command.py
click module is not available in some distros.
This commit removes it usage from the otk_osbuild code.
=> deps: Remove click dependency from `otk_osbuild`

Containerfile
Use the distribution packages in the container instead of downloading them from pypi.
=> container: use distro packages

.pre-commit-config.yaml, src/otk/command.py
add ruff to the pre-commit hook
should be merged *after* #105
=> Pre-commit: enable ruff

src/otk/command.py, src/otk/directive.py, src/otk/document.py, test/test_compile.py, test/test_directive.py, test/test_document.py
The upside of using file descriptors is that there are less TOCTOU issues, i.e. `if not src.exists()` on a path is racy but this can easily be avoided by just opening the file and keeping it open.
It will also make testing for stdin/stdout easier from the test POV there is nothing special about them (i.e. it's not even needed to test that they work just that when "-" is passed on the commandline (or nothing) stdin/stdout is opened).
Note that there is probably more needed but this is enough to satify the tests (but I suspect the recursive loading will break with this change so it might be a good place to add a test with an `otk.include` to ensure this is covered.
=> otk: use file handles instead of paths when reading files

src/otk/tree.py, test/data/base/00-empty.json, test/data/base/00-empty.yaml, test/data/base/01-define.json, test/data/base/01-define.yaml, test/data/base/02-include.json, test/data/base/02-include.yaml, test/data/base/02-include/example.yaml, test/test_directive_sugar.py, test/test_example.py
These examples show simple variants of omnifests, not set up to create a full distribution but only to show functionality.
More complex examples are not working at this point; they will come at a later point as the implementation grows to support them.
=> test: baseline tests

src/otk/directive.py, src/otk/transform.py, test/data/base/09-include-with-var.json, test/data/base/09-include-with-var.yaml, test/test_directive.py, test/test_substitute_vars.py, test/test_transform.py
This PR includes some small refactoring, code cleanups, and a new test.
I also included the first commit from #113 to avoid conflicts.  The second commit I'd like to add later with some changes (for example c6b0b6871b4928ed4b8b1df0b23728a0752821cc).
I renamed the `desugar()` function for clarity.  Quoting the commit message:
> The name `desugar()` was in reference to initial specifications that supported multiple ways of referring to variables and the `${name}` form was considered "syntactic sugar".  Now we only have one way of referring to variables and the concept of "desugaring" might be hard to understand.
>
> Rename it to `replace_vars()` to make its purpose clearer.
=> Small refactors and cleanups in prep for bigger changes

test/test_example.py
While pathlib.Path is much nicer to work with than doing glob.glob() and getting a bunch of strings, when the list of parameters for pytest is a list of strings, you get much nicer test output with the filename in the name of the test and, more importantly, the ability to filter tests based on the name of the yaml file parameter.
Closes #121
=> test: parametrize base examples test with filenames

test/test_directive.py, test/test_substitute_vars.py
Right now there are some tests defined in `test_substitute_vars.py` and some in `test_directive.py`. Move them all into a single file.
[Sorry for the whitespace changes, this is `pre-commit` doing stuff :( Not overly happy about this]
=> test: move all `substitute_vars` tests into `test_substitute_vars.py`

src/otk/error.py, src/otk/transform.py, src/otk/traversal.py, test/data/error/01-circular.err, test/data/error/01-circular.yaml, test/data/error/01-circular/a.yaml, test/data/error/01-circular/b.yaml, test/data/error/01-circular/subdir/c.yaml
Now that we have state during the recursion we can detect circular imports. This commit adds it and a matching test.
=> otk: detect circular imports

.github/workflows/lint.yml, .github/workflows/test.yml, .pre-commit-config.yaml, pyproject.toml
as `pre-commit` only runs on files you currently changed by default `lint.yml` and `test.yml` have been missing...
also suggesting to use autopep8 as it's not that aggressive as `ruff` is (see discussion in https://github.com/osbuild/images/pull/753 )
=> Fix precommit yamllint

src/otk/command.py, src/otk/document.py, src/otk/error.py, src/otk/transform.py, test/data/error/01-circular.yaml, test/test_directive.py, test/test_document.py
A quick draft with some ideas about consolidating some things now that we have a the new recursive core.
---
otk: remove no longer used `include()` and tests
The `transform.include()` helper got superseeded by the new
`process_includes()`.
----
otk: simplify Omnifest and use `process_include` in
entrypoint
With the recent change to require a fully processed tree before
creating the omnifest [0] it seems we can simplify the Omnifest
a bit more now that it essentially is just a container for an
externally resolved tree.
This commit does that by removing some of the entrypoints
like `from_yaml_{file,data}` as those are not that useful
without resolving the tree first.
One nice effect of this change is that the circular import
detection now includes the top-level entrypoint in the error
and …
=> [RFC] use process_include() for main entry point too

src/otk/transform.py, test/data/base/11-define-variants.json, test/data/base/11-define-variants.yaml
**otk: only try to merge dict with dict in defines**
If a key was previously defined in the context's defines but was not a
dict and was instead a list or primitive type, we would try to merge
them, which would break when trying to index the existing value as a
dictionary.
Make sure a subblock is reused only when it's actually a dictionary.  In
all other cases, the new value replaces the old.
---
**test: expand duplicate-define to include replacement cases**
The test now also checks if:
- a dictionary/object definition is replaced when the new value is a
list or a string.
- a list or string definition is replaced when the new value is a
dictionary/object.
- a list or string definition is replaced when the new value is a string
or list (respectively).
---
=> Fix duplicate defines when original value is not a dictionary

src/otk/command.py, src/otk/document.py
There are some places that check for targets, consolidate the target filtering into Omnifest and the error checking too.
=> otk: consolidate target filtering into `Omnifest.targets`

.github/workflows/lint.yml, Makefile
We dropped `ruff` for formatting in #125, lets drop `ruff` from `make lint`; let's use `pre-commit` in CI for the linter to make everything the same everywhere.
=> ci: use pre-commit in actions as well

src/otk/command.py, src/otk/context.py
The path of the project is now tracked in `traversal.State.path` so it can be safely removed from CommonContext().
=> otk: remove `_path` from CommonContext()

src/otk/context.py
These helpers are currently unused and it's not clear (to me) what they do. Let's remove them until we have a use case. But equally happy to add a comment or test if we know how they will be used.
=> context: remove {for,from}_externals() as they are unused

.github/workflows/lint.yml, Makefile, pyproject.toml, src/otk/command.py, src/otk/context.py, src/otk/document.py, src/otk/error.py, src/otk/external.py, src/otk/transform.py, src/otk/tree.py, src/otk_external_osbuild/command.py, test/test_command.py, test/test_compile.py, test/test_context.py, test/test_example.py, test/test_substitute_vars.py, test/test_traversal.py, test/test_validate.py
This commit adds pylint and fixes the various warnings that it triggers. There are still some disabled ones left but this captures many of the low-hanging fruits.
=> many: add `pylint` to linters and fix warnings

doc/03-omnifest/01-directive.md, src/otk/constant.py, src/otk/context.py, src/otk/transform.py, test/test_context.py
This commit adds rules how variables can be named. This is
mostly a defensive measure to avoid ambiguity to disallow
cases that are valid yaml but will may confuse users:
```yaml
otk.define:
a-b: "foo"
key: ${a-b}
```
which is no longer possible with this commit.
=> otk: limit var naming

src/otk/context.py, test/test_substitute_vars.py
The variable lookup in context was missing error information, this commit adds a test and adds the missing error information.
=> context: fix error when a variable lookup does not work

src/otk/context.py, src/otk/transform.py, test/test_substitute_vars.py
This commit adds detection for invalid variable usage in otk. This
means that:
```yaml
foo: ${a-b}
```
will now raise an error instead of being ignored.
It also means that nested var will error. The existing code has some
confusing behavior when nesting ${}, e.g.
```python
def test_sub_var_recursive():
context = CommonContext()
context.define("a", "foo")
context.define("b", "bar")
s = substitute_vars(context, "${a.${b}}")
```
This just no longer works because "$" is not a valid var name inside
a substitution.
[draft as it needs https://github.com/osbuild/otk/pull/143 and https://github.com/osbuild/otk/pull/147 (not strictly)]
=> otk: error when an invalid variable is used in a substitution

.github/workflows/lint.yml, src/otk/command.py, src/otk/context.py, src/otk/external.py, src/otk/target.py, src/otk/traversal.py
There are many type hints but mypy was not happy so this commit makes it clean again and adds it as part of the GH workflow so that we keep it clean. The registries will have to be redone, they are currently not type safe but we only have a single target right now so it's probably okay for now to just use a very simple approach
=> otk: make code `mypy` clean and run as part of the gh actions

src/otk/command.py, src/otk/context.py, test/test_context.py, test/test_integration.py
We describe in `01-directive.md` that we support warnings via `-w duplicate-definition` - this commit makes this real.
[edit: there is also a typo fix in the warning]
=> otk: add support for `otk -w duplicate-definition`

src/otk/traversal.py
This commit switches the the shorter and easier (IMHO) to read typing.Optional[] type and uses that instead of typing.Union[]. The are equivalent otherwise.
=> otk: use typing.Optional instead of Union[,None]

doc/03-omnifest/01-directive.md, src/otk/command.py, test/test_integration.py
otk: add support for `-w all`
Tiny commit to allow to shortcut warning passing by allowing to
do a `-w all` style that just enables all warnings.
---
otk: rename `-w` -> `-W` for warning control
Both gcc and python use `-W` to enable warnings so let's just follow
the same pattern.
=> otk: add support for `-Wall`

pyproject.toml, src/otk/command.py, src/otk/external.py, src/otk/transform.py, src/otk/traversal.py, src/otk/tree.py
Add more `mypy` strictness, especially `disallow_incomplete_defs`
is useful. This follows roughly the suggestions from
https://mypy.readthedocs.io/en/stable/existing_code.html#introduce-stricter-options
The next steps would probably be:
```
check_untyped_defs = true
disallow_untyped_calls = True
disallow_untyped_defs = True
```
but `disallow_untyped_defs` would require to be able to exclude
all the file in `test/` for this specific check as it seems a
bit overkill.
[based on https://github.com/osbuild/otk/pull/154 to avoid conflicts]
=> otk: add more mypy strictness

src/otk/command.py, src/otk/target.py, test/data/log_fatal/00-target-should-not-be-list.err, test/data/log_fatal/00-target-should-not-be-list.yaml, test/data/log_fatal/01-target-should-not-be-string.err, test/data/log_fatal/01-target-should-not-be-string.yaml, test/data/log_fatal/02-target-should-not-contain-version.err, test/data/log_fatal/02-target-should-not-contain-version.yaml, test/test_example.py
checking that target
- is a dict
- contains 'pipelines'
- does not contain 'version'
checking source is unclear to me - so it's a comment for now
=> Implement error for invalid target

src/otk/context.py
It seems like nothing is currently using Context.defines plus there is already a `Context.define()` and a `Context.variable()` which provide similar functionality (and more as they can resolve dotted notation). Unless there is a use-case or a good reason let's remove these methods and bring them back if/when we need them.
=> otk: remove unused "defines"  getter/setter from Context

src/otk/context.py, src/otk/transform.py, test/data/base/13-define-external.json, test/data/base/13-define-external.yaml, test/data/error/03-nonexistent-external.err, test/data/error/03-nonexistent-external.yaml, test/fake_externals.py, test/test_example.py
Adds a test that uses a mocked mirror external that returns the subtree directly inside an `otk.define` block. The variable is not available while it should be.
=> otk,test: support otk.external inside otk.define

src/otk/document.py, test/data/error/03-lonely-keys.err, test/data/error/03-lonely-keys.yaml
This commit disallows top level keys that have no targets and are not `otk.` specific. I.e. it disallows something like:
```yaml
otk.version: 1
otk.target.osbuild:
random:
key: value
```
The rational is that a construct like this may confuse users as the `random:` subtree will not appear in any output or have any other effect.
=> otk: error for top-level keys without targets

test/data/base/00-empty.yaml, test/data/base/01-define.yaml, test/data/base/02-include.yaml, test/data/base/04-op-in-define.yaml, test/data/base/05-target-in-include.yaml, test/data/base/05-target-in-include/example.yaml, test/data/base/06-duplicate-define.yaml, test/data/base/07-double-define.yaml, test/data/base/08-type-define.yaml, test/data/base/09-include-with-var.yaml, test/data/base/09-op.yaml, test/data/base/10-subdefines.yaml, test/data/base/11-define-variants.yaml, test/data/base/12-op-join-type.yaml, test/data/base/13-define-external.yaml, test/data/base/13-include-in-subdir/target.yaml, test/data/error/00-invalid.yaml, test/data/error/02-include-in-define.yaml, test/data/error/03-nonexistent-external.yaml, test/data/error/03-target-should-not-be-list.yaml, test/data/error/04-target-should-not-be-string.yaml, test/data/error/05-target-should-not-contain-version.yaml, test/test_command.py, test/test_example.py
We allow the use of `otk.define.foo` or `otk.target.osbuild.foo`
to ensure when multiple `otk.defines` are done in a single file
it is still valid yaml. However in a lot of our examples we only
have a single `otk.define` in the file or only a single target.
Here there is no need to append a postfix.
This commit simplifies these occurances and removes unneeded
postfixes. They are still valid and some tests needs them but
the are no longer there by default.
We should probably do the same for the `examples/**`.
=> test: simplify naming of yaml/targets

src/otk/command.py, src/otk/transform.py, test/data/base/14-include-regression.json, test/data/base/14-include-regression.yaml, test/data/base/14-include-regression/build.yaml, test/data/base/14-include-regression/centos-9.yaml
This commit fixes the bug that the loop over a dict returns too early for `otk.target` and for `otk.include` - both need to continue iterating over the dict.
As fallout from this the command.py code also needs a tweak and "duplicated_defintion" warnings are now only printed in the final resolve run (not in the target-discovery phase).
A regression test is added based on the excellent example from Simon (thank you!).
=> test: add test that has two includes and fix the resulting fallout

src/otk/transform.py, test/data/error/06-no-two-externals.err, test/data/error/06-no-two-externals.yaml, test/data/error/07-no-two-op-joins.err, test/data/error/07-no-two-op-joins.yaml, test/test_example.py
It is not allowed to have multiple `otk.op` or `otk.external` in the same dict today, add a test that makes this explicit.
Fwiw, it's not clear to me why we disallow this but given that it seems a concious decision let's ensure we not change it by accident.
=> test: add tests for directives that do not allow siblings

src/otk/transform.py, test/data/base/15-double-define-include.json, test/data/base/15-double-define-include.yaml, test/data/base/15-double-define-include/one.yaml, test/data/base/15-double-define-include/two.yaml, test/test_transform.py
This commit fixes the special case that an define can be an empty
dict.
Base on https://github.com/osbuild/otk/pull/173
=> otk: allow `otk.define={"a": {}}`

src/otk/transform.py, test/data/base/16-include-copy.json, test/data/base/16-include-copy.yaml, test/data/base/16-include-copy/repository-9.yaml
When trying to compile the example in PR#167 I noticed slightly strange behavior. Currently when doing:
```yaml
otk.target.osbuild:
otk.include: "16-include-copy/repository-${version}.yaml"
```
the output is
```json
{
'otk.include': '16-include-copy/repository-${version}.yaml',
'sources': {},
'version': '2',
}
```
The reason is that we have an extra `tree.copy()` when we process includes. However in other parts of the code (including accross recursions) we use "tree.update()" so that the tree we worked on and the tree that the other parts of the recursion go out of sync. The easiest fix is to simply drop the copy.
=> otk: fix incorrect tree copy in `otk.include`

doc/03-omnifest/02-external.md, src/otk/external.py, test/fake_externals.py, test/test_external.py
The external name in the schema serves no good purpose.
=> external: drop external name from schema

.pre-commit-config.yaml, Makefile
`pylint` is part of github actions, so it should be checked locally to avoid problems
=> pre-commit: add pylint to be checked

Makefile
Do you think this is too much?
or just leave it up to the users to checkout the README.md
=> Makefile: add hint if pre-commit is not installed

.pre-commit-config.yaml
in markdown a double whitespace at the end of a line is concidered a newline and nothing bad...
I think this should be the default in all repos
=> pre-commit: allow EOL whitespaces in markdown

src/otk/context.py, src/otk/target.py, test/data/base/00-empty.json, test/data/base/01-define.json, test/data/base/02-include.json, test/data/base/04-op-in-define.json, test/data/base/05-target-in-include.json, test/data/base/06-duplicate-define.json, test/data/base/07-double-define.json, test/data/base/08-type-define.json, test/data/base/09-include-with-var.json, test/data/base/09-op.json, test/data/base/10-subdefines.json, test/data/base/11-define-variants.json, test/data/base/12-op-join-type.json, test/data/base/13-define-external.json, test/data/base/13-include-in-subdir.json, test/data/base/14-include-regression.json, test/data/base/15-double-define-include.json, test/data/base/16-include-copy.json, test/data/base/17-include-define.json, test/data/base/18-define-in-target.json, test/test_command.py, test/test_compile.py
Sources are no longer implicit to the osbuild context but will instead be generated explicitly by externals. Remove them from the target, context, and test cases.
I'm splitting out the work of fixing up CentOS started in #169 in separate PRs so #186 can build upon them without it being an unreviewable mess.
=> target: don't write `sources` by default

test/conftest.py, test/test_against_images_refs.py
With the current naming of this class it gets collected by `pytest` and then warns about it:
```
==================================== warnings summary ====================================
test/test_against_images_refs.py:13
/home/user/src/rh/otk/test/test_against_images_refs.py:13: PytestCollectionWarning: cannot collect test class 'TestCase' because it has a __init__ constructor (from: test/test_against_images_refs.py)
class TestCase:
```
=> test: rename testcase

Makefile
This commit adds a new "make external" command that should help iterate faster by making the images otk externals available easily for development.
[split out from https://github.com/osbuild/otk/pull/185 to unblock the external development]
=> Makefile: add "make external" to have a quick way to build externals

test/data/images-ref/centos/9/x86_64/ami/centos_9-x86_64-ami-empty.yaml, test/data/images-ref/centos/9/x86_64/qcow2/centos_9-x86_64-qcow2-empty.yaml, test/data/images-ref/fedora/40/aarch64/minimal-raw/fedora_40-aarch64-minimal_raw-empty.yaml, test/data/images-ref/fedora/40/x86_64/minimal-raw/fedora_40-x86_64-minimal_raw-empty.yaml, test/data/images-ref/gen-image-def
When generating the "images" library reference yaml we used the
default yaml.dump() implementation. This will reoder the keys
which is undesirable for us as it moves e.g. the `type: ...`
key at the end of a block. But in a osbuild manifest this is
the one of the most important pieces of information.
So this commit changes the code to not sort the yaml keys.
---
test: re-generate the reference images with yaml
`sort_keys=False`
Trivial update to use the previous commit:
```
./gen-image-def ~/devel/osbuild/images centos 9 x86_64 ami
./gen-image-def ~/devel/osbuild/images fedora 40 x86_64 minimal_raw
./gen-image-def ~/devel/osbuild/images fedora 40 x86_64 minimal-raw
./gen-image-def ~/devel/osbuild/images fedora 40 aarch64 minimal-raw
```
=> test: use `sort_keys=False` in the `gen-image-def` helper

example/centos/centos-9-x86_64-ami.yaml, example/centos/centos-9-x86_64-qcow2.yaml, example/fedora/fedora-40-aarch64-minimal-raw.yaml, example/fedora/fedora-40-x86_64-minimal-raw.yaml
This commit just uses the now sorted "images" reference images in the example, preparing for the external usage.
=> example: use the newly sorted "images" reference images

.github/workflows/test.yml, Makefile, example/centos/centos-9-x86_64-qcow2.yaml, example/centos/common/gen-partition-table-x86_64.yaml, test/data/images-ref/centos/9/x86_64/qcow2/centos_9-x86_64-qcow2-empty.yaml, test/data/images-ref/gen-image-def, test/test_against_images_refs.py
workflow: ensure "make test" builds externals and use in
workflow
This commit ensures that externals are build during the tests and
that the GH action will test with externals too.
This is slightly hacky as it requires the network. Eventually we
can pull in externals via build-deps or vendor them but for now
this unblocks the otk work.
---
example: port `centos-9-x86_64-qcow2.yaml` to use partition
externals
This commit uses the various externals to generate partition tables
in the qcow2 image.
---
test: use `OTK_EXTERNAL_PATH` in test_images_ref
Use the locally donwloaded/build `external` in this test to ensure
that the otk acually finds externals.
--- 
test: workaround different RNG results in `gen-manifests`
This is a hacky commit - the OSBUILD_TESTING_RNG_SEED is set for both …
=> example: port `centos-9-x86_64-qcow2.yaml` to use partition  externals

example/centos/common/gen-partition-table-x86_64.yaml
The reference partition table for `centos9-x86_64` in [0] has some small divergence:
- different root size
- remove some `XXX` (for now)
This commit fixes this.
[0] https://github.com/osbuild/images/blob/v0.85.0/pkg/distro/rhel/rhel9/partition_tables.go#L25
=> example: tweak `centos9-x86_64` partioning to match upstream

example/centos/centos-9-x86_64-ami.yaml, example/centos/centos-9-x86_64-qcow2.yaml, example/centos/fragment/grub2.yaml, test/data/images-ref/centos/9/x86_64/ami/centos_9-x86_64-ami-empty.yaml, test/data/images-ref/gen-image-def
This PR uses the partition externals in the `example/centos/centos-9-x86_64-ami.yaml` too. As part of this the grub2 stage fragment got also extracted to avoid some obvious duplication.
=> example: extract `grub2` and ue `partition` external in centos9 ami too

Makefile, example/centos/centos-9-x86_64-ami.yaml, example/centos/centos-9-x86_64-qcow2.yaml
Makefile: add new `make-grub2-inst-stage` external
This adds the new `make-grub2-inst-stage` that was added to images
in https://github.com/osbuild/images/pull/916.
---
example: use new `otk-make-grub2-inst-stage` stage in centos
Use the new `otk-make-grub2-inst-stage` to remove hardcoded
values from the centos examples.
=> Use new `otk-make-grub2-inst-stage` stage in centos

Makefile, example/centos/centos-9-x86_64-ami.yaml, example/centos/centos-9-x86_64-qcow2.yaml, pyproject.toml, test/test_against_images_refs.py
This is another splitout of #196 - now that we have the resolver we use it in the otk files.
[draft as I think we want to de-duplicate and sort the packages list]
=> example: centos9-qcow/ami with depsolve

Makefile
Include the recently merged container resolver and ostree commit resolver externals.
Necessary for #206, was implemented in: https://github.com/osbuild/images/pull/936 and https://github.com/osbuild/images/pull/935
=> make: include new externals

example/centos/centos-9-aarch64-qcow2.yaml, example/centos/centos-9-aarch64-tar.yaml, example/centos/centos-9-ppc64le-tar.yaml, example/centos/centos-9-s390x-tar.yaml, example/centos/centos-9-x86_64-qcow2.yaml, example/centos/centos-9-x86_64-tar.yaml, example/centos/pipeline/build/generic.yaml, example/centos/pipeline/build/tar.yaml, example/centos/pipeline/tar.yaml, test/data/images-ref/centos/9/aarch64/tar/centos_9-aarch64-tar-empty.json, test/data/images-ref/centos/9/aarch64/tar/centos_9-aarch64-tar-empty.yaml, test/data/images-ref/centos/9/ppc64le/tar/centos_9-ppc64le-tar-empty.json, test/data/images-ref/centos/9/ppc64le/tar/centos_9-ppc64le-tar-empty.yaml, test/data/images-ref/centos/9/s390x/tar/centos_9-s390x-tar-empty.json, test/data/images-ref/centos/9/s390x/tar/centos_9-s390x-tar-empty.yaml, test/data/images-ref/centos/9/x86_64/tar/centos_9-x86_64-tar-empty.json, test/data/images-ref/centos/9/x86_64/tar/centos_9-x86_64-tar-empty.yaml
Tar pipelines for all architectures, based on #209.
=> example/centos: tar for x86, aarch64, s390x, and ppc64le

src/otk_external_osbuild/command/make_depsolve_dnf4_rpm_stage.py, test/test_make_depsolve_dnf4_rpm_stage.py
Allow the passing of options for the RPM stage. Some of our omnifests will need to do this (e.g. `edge-commit` turns off `dracut` and some other bits and bobs).
=> external/depsolve: allow passing options for rpm

test/data/images-ref/centos/9/aarch64/ami/centos_9-aarch64-ami-empty.yaml, test/data/images-ref/centos/9/aarch64/qcow2/centos_9-aarch64-qcow2-empty.yaml, test/data/images-ref/gen-image-def, test/test_against_images_refs.py
This commit tweaks the gen-images-ref to be slightly smarter
about how to handle UUIDs. Instead of the extremly naive table
of uuids generated by "images" and "gen-partition-table" it now
tries to figure out the UUID from images via the "mkfs" stage
of the manifest. This is also a bit (f)ugly but avoids some
busywork.
Hopefully we find a better way but this should give us some
time.
=> test: tweak gen-images() to be smarter about the UUID hacks

example/centos/centos-9-aarch64-edge-commit.yaml, example/centos/centos-9-x86_64-edge-commit.yaml, test/data/images-ref/centos/9/aarch64/edge-commit/centos_9-aarch64-edge_commit-empty.yaml, test/data/images-ref/centos/9/x86_64/edge-commit/centos_9-x86_64-edge_commit-empty.yaml
Same as others; based on #215 so draft first.
=> example: edge-commit for x86/aarch64

.gitignore, Containerfile, Makefile, README.md
Does it make sense to create a container for now which "just works"?
(related to #221)
This version of the container includes `otk` and all external commands to have it working for now.
build with
```
podman build --tag otk --pull=newer .
```
run e.g. with
```
podman run --rm -ti -v .:/app otk:latest compile /app/example/centos/centos-9-x86_64-tar.yaml
```
=> Containerfile: include externals in the container

example/centos/centos-9-aarch64-qcow2.yaml, example/centos/centos-9-ppc64le-tar.yaml, example/centos/common/repositories/x86_64.yaml, src/otk_external_osbuild/command/gen_depsolve_dnf4.py, test/data/images-ref/centos/9/aarch64/ami/centos_9-aarch64-ami-empty.yaml, test/data/images-ref/centos/9/aarch64/edge-commit/centos_9-aarch64-edge_commit-empty.yaml, test/data/images-ref/centos/9/aarch64/qcow2/centos_9-aarch64-qcow2-empty.yaml, test/data/images-ref/centos/9/aarch64/tar/centos_9-aarch64-tar-empty.yaml, test/data/images-ref/centos/9/ppc64le/tar/centos_9-ppc64le-tar-empty.yaml, test/data/images-ref/centos/9/s390x/tar/centos_9-s390x-tar-empty.yaml, test/data/images-ref/centos/9/x86_64/ami/centos_9-x86_64-ami-empty.yaml, test/data/images-ref/centos/9/x86_64/edge-commit/centos_9-x86_64-edge_commit-empty.yaml, test/data/images-ref/centos/9/x86_64/qcow2/centos_9-x86_64-qcow2-empty.yaml, test/data/images-ref/centos/9/x86_64/tar/centos_9-x86_64-tar-empty.yaml, test/test_gen_depsolve_dnf4.py
This PR uses the new pseudo repos generated via https://github.com/osbuild/images/pull/944
[draft as the tests fail currently, I suspect because the repos needs fixing/updating]
=> many: use new "pseudo" repos from images

.gitignore, Makefile, otk.spec
This fixes the Makefile and introduces new targets.
e.g. `make test` now also sets up the venv and externals
Now the following rules should be working:
* help: new
* clean: new - be aware this also removes venv as it will be rebuilt anyway
* test: did not setup the environment before
* rpm: was failing in the current version
also updates `.gitignore` to match (so [this](https://github.com/osbuild/otk/pull/220#issuecomment-2371727229) is obsolete)
=> Implement makefile building from scratch

example/centos/centos-9-aarch64-image-installer.yaml, example/centos/centos-9-x86_64-ami.yaml, example/centos/centos-9-x86_64-qcow2.yaml, example/centos/fragment/grub2/x86_64.yaml
This commit adds the `${kernel.package...}` feature for grub2 for x86_64 similar to aarch64. It also adds some TODO in the other places that we need the kernel version and currently hardcoding it.
=> example: use `${kernel.package...}` more consistently

pyproject.toml, src/otk_external_osbuild/command/gen_inline_files.py, src/otk_external_osbuild/command/make_inline_source.py, test/test_gen_inline_files.py, test/test_make_inline_source.py
This PR adds two externals:
**external: add new `gen-inline-files` external**
Will be used to generate inline files for manifests.
To add a file in a manifest as in-line content we need an ID, which is
the sha256 hash of the contents and the file contents in base64.
**external: add new `make-inline-source` external**
Takes the output from gen-inline-files and generates the
org.osbuild.inline source structure for the manifest.
=> Add externals for managing embedded files

example/centos/centos-9-aarch64-image-installer.yaml, example/centos/centos-9-x86_64-image-installer.yaml
This commit moves the image installer to use the
`osbuild-get-dnf4-package-info` external to get details about
the kernel version and use that in the anaconda pipeline.
[draft as this requires https://github.com/osbuild/otk/pull/236 and I also want someone experienced with images to double check, I'm 85% confident that picking the kernel version from the anaconda packageset is the right move but we cannot differenciate this in our tests right now so it requires (careful) manual checking.
=> example: drop hardcoding kernel version from image-isntaller

example/centos/centos-9-aarch64-minimal-raw.yaml, example/centos/centos-9-x86_64-minimal-raw.yaml, example/centos/common/partition-table/aarch64/minimal-raw.yaml, example/centos/common/partition-table/x86_64/minimal-raw.yaml, example/centos/fragment/grub2/x86_64-no-bios.yaml, example/centos/pipeline/image/x86_64-no-bios.yaml, test/data/images-ref/centos/9/aarch64/minimal-raw/centos_9-aarch64-minimal_raw-empty.yaml, test/data/images-ref/centos/9/x86_64/minimal-raw/centos_9-x86_64-minimal_raw-empty.yaml
Generated manifests and initial deduplication for the minimal-raw image type.
A new partition table is added for the minimal raw images.
Since the x86_64 images here don't support BIOS booting some includes had to be split into non-BIOS versions.
Based on #219.
=> example/centos: import minimal-raw

src/otk_external_osbuild/command/get_dnf4_package_info.py, test/test_get_dnf4_package_info.py
Make the package name available in the package info external. This can then be used for (for example) the sysconfig deduplication or other places that need the kernel name *without* introducing an extra variable elsewhere.
=> external: make package name avaiable

.pre-commit-config.yaml, .yamllint, src/otk/error.py, src/otk/transform.py, test/data/error/09-duplicated-key.err, test/data/error/09-duplicated-key.yaml, test/data/error/10-duplicated-key-no-otk.err, test/data/error/10-duplicated-key-no-otk.yaml
This commit will make the yaml loader error when duplicated yaml keys are used. This can easily happen with e.g.:
```yaml
otk.include: foo.yaml
...
[lots of stuff]
...
otk.include: bar.yaml
```
with the default yaml loader this would make the value of `otk.include=bar.yaml` which leads to confusing and hard to understand errors. Best is to simply error with a reasonable error message.
The correct way in otk to write this would be:
```
otk.include.foo: foo.yaml
...
otk.include.bar: bar.yaml
```
This will now yield errors like:
```
...
file .../otk/test/data/error/09-duplicated-key.yaml has duplicated yaml keys: duplicate 'otk.include' key found, try using otk.include.<uniq-tag>, e.g. otk.include.foo
```
Note that this PR also removes one of the `yaml` linters (`check-yaml`), see the …
=> otk: do not allow duplicated yaml keys

example/centos/centos-9-aarch64-ami.yaml, example/centos/centos-9-aarch64-edge-commit.yaml, example/centos/centos-9-aarch64-minimal-raw.yaml, example/centos/centos-9-aarch64-qcow2.yaml, example/centos/centos-9-aarch64-tar.yaml, example/centos/centos-9-aarch64-vhd.yaml, example/centos/centos-9-ppc64le-tar.yaml, example/centos/centos-9-s390x-tar.yaml, example/centos/centos-9-x86_64-ami.yaml, example/centos/centos-9-x86_64-edge-commit.yaml, example/centos/centos-9-x86_64-minimal-raw.yaml, example/centos/centos-9-x86_64-ova.yaml, example/centos/centos-9-x86_64-qcow2.yaml, example/centos/centos-9-x86_64-tar.yaml, example/centos/centos-9-x86_64-vhd.yaml, example/centos/centos-9-x86_64-vmdk.yaml, example/centos/fragment/locale.yaml
Introduce a locale fragment that fills in an osbuild locale stage with a global define.
Note that the image-installer omnifests are excluded as they currently have dual locales so can't use a single global define.
Split out (and updated) from #240.
=> example/centos: locale fragment

example/centos/centos-9-aarch64-ami.yaml, example/centos/centos-9-aarch64-edge-commit.yaml, example/centos/centos-9-aarch64-image-installer.yaml, example/centos/centos-9-aarch64-minimal-raw.yaml, example/centos/centos-9-aarch64-qcow2.yaml, example/centos/centos-9-aarch64-tar.yaml, example/centos/centos-9-aarch64-vhd.yaml, example/centos/centos-9-ppc64le-tar.yaml, example/centos/centos-9-s390x-tar.yaml, example/centos/centos-9-x86_64-ami.yaml, example/centos/centos-9-x86_64-edge-commit.yaml, example/centos/centos-9-x86_64-image-installer.yaml, example/centos/centos-9-x86_64-minimal-raw.yaml, example/centos/centos-9-x86_64-ova.yaml, example/centos/centos-9-x86_64-qcow2.yaml, example/centos/centos-9-x86_64-tar.yaml, example/centos/centos-9-x86_64-vhd.yaml, example/centos/centos-9-x86_64-vmdk.yaml, example/centos/fragment/fix-bls/default.yaml, example/centos/fragment/fix-bls/empty-prefix.yaml
Introduce a new fix-bls fragment that comes in two variants, one with an empty prefix and one with the default options selected. Perhaps this can be further deduplicated later on (doing this based on a modification?).
Split out from #240.
=> example/centos: fix-bls fragment

example/centos/centos-9-aarch64-ami.yaml, example/centos/centos-9-aarch64-minimal-raw.yaml, example/centos/centos-9-aarch64-qcow2.yaml, example/centos/centos-9-aarch64-vhd.yaml, example/centos/centos-9-x86_64-ami.yaml, example/centos/centos-9-x86_64-minimal-raw.yaml, example/centos/centos-9-x86_64-ova.yaml, example/centos/centos-9-x86_64-qcow2.yaml, example/centos/centos-9-x86_64-vhd.yaml, example/centos/centos-9-x86_64-vmdk.yaml, example/centos/fragment/kernel-cmdline.yaml
New fragment that requires `kernel.cmdline` and the partition external to be in use. Split off from #240.
=> example/centos: kernel-cmdline fragment

test/data/images-ref/gen-image-def
This commit changes the `gen-image-def` script to use the `org.osbuild.fstab` stage to find the UUIDs of the root and boot partitions. We used to use the `mkfs.*` stage and the `label` parameter but it turns out that `s390x` and `ppc64le` do not use the label paramter so the UUID is not found.
Thanks to Florian Schüller <florian.schueller@redhat.com> for finding and testing.
=> test: use `fstab` stage in `gen-image-def` to find UUIDs

example/centos/centos-9-aarch64-ami.yaml, example/centos/centos-9-aarch64-edge-commit.yaml, example/centos/centos-9-aarch64-image-installer.yaml, example/centos/centos-9-aarch64-minimal-raw.yaml, example/centos/centos-9-aarch64-qcow2.yaml, example/centos/centos-9-aarch64-tar.yaml, example/centos/centos-9-aarch64-vhd.yaml, example/centos/centos-9-aarch64-wsl.yaml, example/centos/centos-9-ppc64le-tar.yaml, example/centos/centos-9-s390x-tar.yaml, example/centos/centos-9-x86_64-ami.yaml, example/centos/centos-9-x86_64-edge-commit.yaml, example/centos/centos-9-x86_64-image-installer.yaml, example/centos/centos-9-x86_64-minimal-raw.yaml, example/centos/centos-9-x86_64-ova.yaml, example/centos/centos-9-x86_64-qcow2.yaml, example/centos/centos-9-x86_64-tar.yaml, example/centos/centos-9-x86_64-vhd.yaml, example/centos/centos-9-x86_64-vmdk.yaml, example/centos/centos-9-x86_64-wsl.yaml, example/centos/fragment/grub2/x86_64-no-bios.yaml
A variable containing the targeted architecture makes omnifests less error prone to write. Split out from #240.
=> example/centos: introduce `${architecture}`

src/otk/context.py, test/test_substitute_vars.py
until now the error message was like this:
`otk.error.TransformVariableLookupError: could not find ['fs_options', 'devices', 'device', 'options', 'start']`
with this PR the error helps in finding which fragment is the problem:
`otk.error.TransformVariableLookupError: could not resolve 'fs_options.devices.device.options.start' as 'device' is not defined`
Do you think this change is useful?
=> src/otk/context.py: improve error on missing entry in a dictionary

src/otk_external_osbuild/command/gen_depsolve_dnf4.py, test/data/images-ref/centos/9/aarch64/ami/centos_9-aarch64-ami-empty.yaml, test/data/images-ref/centos/9/aarch64/edge-commit/centos_9-aarch64-edge_commit-empty.yaml, test/data/images-ref/centos/9/aarch64/image-installer/centos_9-aarch64-image_installer-empty.yaml, test/data/images-ref/centos/9/aarch64/minimal-raw/centos_9-aarch64-minimal_raw-empty.yaml, test/data/images-ref/centos/9/aarch64/qcow2/centos_9-aarch64-qcow2-empty.yaml, test/data/images-ref/centos/9/aarch64/tar/centos_9-aarch64-tar-empty.yaml, test/data/images-ref/centos/9/aarch64/vhd/centos_9-aarch64-vhd-empty.yaml, test/data/images-ref/centos/9/aarch64/wsl/centos_9-aarch64-wsl-empty.yaml, test/data/images-ref/centos/9/ppc64le/tar/centos_9-ppc64le-tar-empty.yaml, test/data/images-ref/centos/9/s390x/tar/centos_9-s390x-tar-empty.yaml, test/data/images-ref/centos/9/x86_64/ami/centos_9-x86_64-ami-empty.yaml, test/data/images-ref/centos/9/x86_64/edge-commit/centos_9-x86_64-edge_commit-empty.yaml, test/data/images-ref/centos/9/x86_64/image-installer/centos_9-x86_64-image_installer-empty.yaml, test/data/images-ref/centos/9/x86_64/minimal-raw/centos_9-x86_64-minimal_raw-empty.yaml, test/data/images-ref/centos/9/x86_64/oci/centos_9-x86_64-oci-empty.yaml, test/data/images-ref/centos/9/x86_64/ova/centos_9-x86_64-ova-empty.yaml, test/data/images-ref/centos/9/x86_64/qcow2/centos_9-x86_64-qcow2-empty.yaml, test/data/images-ref/centos/9/x86_64/tar/centos_9-x86_64-tar-empty.yaml, test/data/images-ref/centos/9/x86_64/vhd/centos_9-x86_64-vhd-empty.yaml, test/data/images-ref/centos/9/x86_64/vmdk/centos_9-x86_64-vmdk-empty.yaml, test/data/images-ref/centos/9/x86_64/wsl/centos_9-x86_64-wsl-empty.yaml, test/test_gen_depsolve_dnf4.py
This follows https://github.com/osbuild/images/pull/968 to include the architecture name in the generated URLs so that we can test for things like https://github.com/osbuild/otk/pull/255/files#r1782953752
This also requires a rebuild of all reference manifests.
=> external: add architecture to the gen-depsolve-dnf4 mocks

src/otk/context.py, src/otk/external.py, src/otk/transform.py, src/otk/tree.py, test/test_context.py, test/test_external.py, test/test_substitute_vars.py
otk: add file to variable substitution errors too
This commit adds file context for errors from variable substitution
too.
----
context: tweak erros and add tests for context lookup errors
This commit tweaks the error message for the conext generated
errors and adds tests.
----
otk: include `state` in errors from externals
When an external fails, include the file that called the external
as well by just reusing the new OTKError(state=state) exceptions.
This also adds a test for the external errors and tweaks the
exception a bit based on the test output.
=> otk: more error context improvements

src/otk/external.py, test/test_external.py
Split the OTK_EXTERNAL_PATH on `:` like normal shell path handling in order to enable adding multiple external paths via the environment. Also adds a test for the new behavior.
=> external: Support multiple external paths

Containerfile
Build with a container that has Go 1.22 which is required by `images`.
=> container: fix build

Makefile
if a command fails in "ONESHELL" mode the script continues and
`make` possibly returns `0` instead of a failure
=> Fix makefile returncode

Makefile
When running `make external` not all externals are created right now, only the go ones. This commit ensures all are available inside the `./external` dir.
Not sure this is 100% correct, the makefile grew quite a bit please double check
=> Makefile: add pyexternals target

Containerfile
After the introduction of `pyexternals` as a dependency to `external` in the Makefile targets the Go container also wants to build Python externals.
Let's instead turn everything into a single build container.
=> container: unsplit build containers

Makefile
Include the recently merged [1] external to create ostree source references.
[1]: https://github.com/osbuild/images/pull/960/files
=> otk/external: `osbuild-make-ostree-source`

.github/workflows/test.yml, Makefile
Avoid regressions where building the container breaks
Followup of #273 
let's see how much this slows down the tests
=> github/workflows/test: add test to build the container

README.md
I missed this in #276 review and we accidentally have double Project headings now. Let's merge them, cc @lzap.
=> readme: deduplicate projects

example/centos/centos-9-aarch64-image-installer.yaml, example/centos/centos-9-x86_64-image-installer.yaml
This is a small followup for PR#247, specifically the comment https://github.com/osbuild/otk/pull/247#pullrequestreview-2339846865
TL;DR the locale in the os pipeline is influenced by the image customizations so this commit reflects this now. The other locale set in the anaconda tree is hardcoded, a comment for this is now also added.
=> example: add modifications.locale to image-installer

pyproject.toml, src/otk/__init__.py, src/otk/command.py, test/test_command.py
Adds the dynamic versioning scheme supported by our build system; also adds a new `-V/--version` to the root `otk` command.
=> plumbing: package python versions

src/otk/command.py
Sometimes in my local IDE testing, the lazy close
of the dst file, leads to the test failing because it's not (yet) seeing the result.
So we'll close it, when done.
=> otk/command: fix racecondition in tests

Containerfile
When copying in artifacts from the build stage of the container things need to happen in a specific order. Since `/src/external` contains Python stubs that contain a virtual environment specific shebang.
If we copy the installed Python externals *after* we overwrite the ones with broken shebangs.
Closes #284.
Alternatively we could split out the external building into `go` and `python` for the container build as well.
=> container: fix up build

src/otk/command.py, src/otk/document.py, test/test_command.py, test/test_compile.py, test/test_example.py, test/test_preload.py, test/test_validate.py
Allow defining variables from external sources such as the command-line.
This can be used for customizations (see #242) and build systems to provide, for example, repositories.
```bash
otk compile something.yaml omnifest.yaml
```
(needs additional testcase)
=> externally provided variables

example/centos/centos-9-aarch64-ami.yaml, example/centos/centos-9-aarch64-edge-commit.yaml, example/centos/centos-9-aarch64-image-installer.yaml, example/centos/centos-9-aarch64-minimal-raw.yaml, example/centos/centos-9-aarch64-qcow2.yaml, example/centos/centos-9-aarch64-tar.yaml, example/centos/centos-9-aarch64-vhd.yaml, example/centos/centos-9-aarch64-wsl.yaml, example/centos/centos-9-ppc64le-tar.yaml, example/centos/centos-9-s390x-qcow2.yaml, example/centos/centos-9-s390x-tar.yaml, example/centos/centos-9-x86_64-ami.yaml, example/centos/centos-9-x86_64-edge-commit.yaml, example/centos/centos-9-x86_64-image-installer.yaml, example/centos/centos-9-x86_64-minimal-raw.yaml, example/centos/centos-9-x86_64-ova.yaml, example/centos/centos-9-x86_64-qcow2.yaml, example/centos/centos-9-x86_64-tar.yaml, example/centos/centos-9-x86_64-vhd.yaml, example/centos/centos-9-x86_64-vmdk.yaml, example/centos/centos-9-x86_64-wsl.yaml, pyproject.toml, src/otk_external_osbuild/command/make_generator_metadata.py, test/test_against_images_refs.py, test/test_make_generator_metadata.py
`osbuild` [grew](https://github.com/osbuild/osbuild/pull/1900) the ability to include generator metadata. Let's actually write that metadata in `otk`.
=> generator metadata

doc/03-omnifest/index.md
The import in docs [1] highlighted this anchors name being wrong.
[1]: https://github.com/osbuild/osbuild.github.io/pull/129
=> doc: fix anchor
